version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: rgym-mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: rgym-db

volumes:
  mongo-data:
